name: Deploy Website

on:
  push:
    paths-ignore:
      - '**/README.md'
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install html-minifier-terser clean-css-cli -g

    - name: Minify HTML
      run: |
        find ./website -name "*.html" -exec html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true -o {}.min {} \;
        find ./website -name "*.html.min" -exec sh -c 'mv "$0" "${0%.min}"' {} \;

    - name: Minify CSS
      run: cleancss -o ./website/dist/style.css ./website/style.css

    - name: Create dist directory
      run: mkdir -p ./website/dist

    - name: Copy other files
      run: |
        cp ./website/index.html ./website/dist/index.html
        cp -r ./website/assets ./website/dist/assets
        cp -r ./website/error ./website/dist/error
        cp -r ./website/projects ./website/dist/projects
        cp -r ./website/sitemap.xml ./website/dist/sitemap.xml

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      shell: bash

    - name: Deploy to Server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        scp -P $SSH_PORT -r ./website/dist/* $SSH_USER@$SSH_HOST:/var/www/html
        ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "chmod -R 755 /var/www/html"
      shell: bash
