name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install html-minifier-terser clean-css-cli -g

    - name: Minify HTML
      run: html-minifier-terser --input-dir ./website --output-dir ./website/dist --collapse-whitespace --remove-comments --minify-css true --minify-js true

    - name: Minify CSS
      run: cleancss -o ./website/dist/style.css ./website/style.css

    - name: Copy other files
      run: |
        cp ./website/index.html ./website/dist/index.html
        cp -r ./website/icons ./website/dist/icons
        cp -r ./website/favicon.ico ./website/dist/favicon.ico

    - name: Setup SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
      shell: bash

    - name: Deploy to Server
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
      run: |
        scp -P $SSH_PORT -r ./website/dist/* $SSH_USER@$SSH_HOST:/var/www/your_website_directory/
        ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "chmod -R 755 /var/www/your_website_directory/"
      shell: bash
